# Generated by Django 4.2.20 on 2025-04-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('categorie', models.CharField(max_length=100)),
                ('disponibilite', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='livres/')),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('lecteur', 'Lecteur'), ('bibliothecaire', 'Bibliothecaire')], max_length=50)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='biblio_smart.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblio_smart.utilisateur')),
            ],
            bases=('biblio_smart.utilisateur',),
        ),
        migrations.CreateModel(
            name='Lecteur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblio_smart.utilisateur')),
            ],
            bases=('biblio_smart.utilisateur',),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_smart.livre')),
                ('lecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_smart.lecteur')),
            ],
        ),
        migrations.CreateModel(
            name='Amende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('statut', models.BooleanField(default=False)),
                ('emprunt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblio_smart.emprunt')),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='liste_attente',
            field=models.ManyToManyField(blank=True, to='biblio_smart.lecteur'),
        ),
    ]
