# Generated by Django 5.2 on 2025-04-06 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('lecteur', 'Lecteur'), ('bibliothecaire', 'Bibliothecaire')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('date_retour', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('categorie', models.CharField(max_length=100)),
                ('disponibilite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblio_smart.utilisateur')),
            ],
            bases=('biblio_smart.utilisateur',),
        ),
        migrations.CreateModel(
            name='Lecteur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblio_smart.utilisateur')),
            ],
            bases=('biblio_smart.utilisateur',),
        ),
        migrations.CreateModel(
            name='Amende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('statut', models.BooleanField(default=False)),
                ('emprunt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblio_smart.emprunt')),
            ],
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_smart.livre'),
        ),
        migrations.AddField(
            model_name='livre',
            name='liste_attente',
            field=models.ManyToManyField(blank=True, to='biblio_smart.lecteur'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='lecteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_smart.lecteur'),
        ),
    ]
