# Generated by Django 5.2 on 2025-04-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_smart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livres/static/images/'),
        ),
    ]
