# Generated by Django 4.2.20 on 2025-04-27 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_smart', '0002_livre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='date_ajout',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='date_modification',
            field=models.DateField(auto_now=True),
        ),
    ]
