# Generated by Django 5.2 on 2025-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_smart', '0002_livre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livres/'),
        ),
    ]
