# Generated by Django 4.2.20 on 2025-04-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_smart', '0004_alter_livre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livres/static/images/'),
        ),
    ]
