# Generated by Django 4.2.20 on 2025-04-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_smart', '0003_alter_livre_image'),
        ('biblio_smart', '0005_alter_livre_image'),
    ]

    operations = [
    ]
