# Generated by Django 4.2.20 on 2025-04-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_smart', '0006_merge_0003_alter_livre_image_0005_alter_livre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
